version: '3.8'

networks:
  superkart_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend_files
      dockerfile: Dockerfile
    container_name: superkart-backend
    ports:
      - "7860:7860"
    networks:
      - superkart_network
    environment:
      - PORT=7860
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend_files
      dockerfile: Dockerfile
    container_name: superkart-frontend
    ports:
      - "8501:7860"
    networks:
      - superkart_network
    environment:
      - BACKEND_URL=http://superkart-backend:7860
    depends_on:
      - backend
    restart: unless-stopped
